# all jobs must pass on both the `staging` commit and the PRâ€™s CI
# before merging
status = [
  "Rust (ubuntu-latest)",
  "Rust (windows-latest)",
  "Rust (macos-latest)",
  "Formatting",
] 
pr_status = [
  "Rust (ubuntu-latest)",
  "Rust (windows-latest)",
  "Rust (macos-latest)",
  "Formatting",
] 

timeout_sec = 600 # CI must take at most ten minutes
use_squash_merge = true
