[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "terminal"
version = "0.0.0"

[dependencies]
anyhow = "1.0"
crossterm = "0.24.0"
unicode-width = "0.1.8"

[dependencies.flume]
default_features = false
version = "0.10.2"
