[package]
edition = "2018"
license = "MIT OR Apache-2.0"
name = "pipes-rs"
version = "1.4.5"

[dependencies]
anyhow = "1.0.37"
etcetera = "0.3.2"
mimalloc = {version = "0.1.25", default-features = false}
model = {path = "../model"}
rng = {path = "../rng"}
serde = "1.0.118"
structopt = "0.3.21"
terminal = {path = "../terminal"}
toml = "0.5.8"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
harness = false
name = "one_frame"
